<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0F6Jo2C\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0F6Jo2C/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container0F6Jo2C.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container0F6Jo2C\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container0F6Jo2C\App_KernelProdContainer([
    'container.build_hash' => '0F6Jo2C',
    'container.build_id' => '77702f3a',
    'container.build_time' => 1733149916,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container0F6Jo2C');
