<?php

namespace ContainerAP0vP6P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\DeleteService' shared autowired service.
     *
     * @return \App\Service\DeleteService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'DeleteService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\DeleteService'])) {
            return $container->privates['App\\Service\\DeleteService'];
        }

        return $container->privates['App\\Service\\DeleteService'] = new \App\Service\DeleteService($a);
    }
}
