<?php

namespace ContainerAP0vP6P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEtudiantApiControllersendStudentsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.StOMeRL.App\Controller\API\EtudiantApiController::sendStudents()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.StOMeRL.App\\Controller\\API\\EtudiantApiController::sendStudents()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'studentRepository' => ['privates', 'App\\Repository\\StudentsRepository', 'getStudentsRepositoryService', true],
            'serializer' => ['privates', 'debug.serializer', 'getDebug_SerializerService', false],
        ], [
            'studentRepository' => 'App\\Repository\\StudentsRepository',
            'serializer' => '?',
        ]))->withContext('App\\Controller\\API\\EtudiantApiController::sendStudents()', $container);
    }
}
