<?php

namespace ContainerAP0vP6P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GOh.w0m.App\Controller\TaskController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GOh.w0m.App\\Controller\\TaskController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'task' => ['privates', '.errored..service_locator.GOh.w0m.App\\Entity\\Task', NULL, 'Cannot autowire service ".service_locator.GOh.w0m": it needs an instance of "App\\Entity\\Task" but this type has been excluded in "config/services.yaml".'],
            'deleteService' => ['privates', 'App\\Service\\DeleteService', 'getDeleteServiceService', true],
        ], [
            'task' => 'App\\Entity\\Task',
            'deleteService' => 'App\\Service\\DeleteService',
        ]))->withContext('App\\Controller\\TaskController::delete()', $container);
    }
}
