<?php

namespace ContainerAP0vP6P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskApiControllerfindByIdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KFjOq3Z.App\Controller\API\TaskApiController::findById()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KFjOq3Z.App\\Controller\\API\\TaskApiController::findById()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'task' => ['privates', '.errored..service_locator.KFjOq3Z.App\\Entity\\Task', NULL, 'Cannot autowire service ".service_locator.KFjOq3Z": it needs an instance of "App\\Entity\\Task" but this type has been excluded in "config/services.yaml".'],
        ], [
            'task' => 'App\\Entity\\Task',
        ]))->withContext('App\\Controller\\API\\TaskApiController::findById()', $container);
    }
}
