<?php

namespace ContainerAP0vP6P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserApiControllerloginService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uP.P_Zl.App\Controller\API\UserApiController::login()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uP.P_Zl.App\\Controller\\API\\UserApiController::login()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'userPasswordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'repository' => 'App\\Repository\\UserRepository',
            'userPasswordHasher' => '?',
            'em' => '?',
        ]))->withContext('App\\Controller\\API\\UserApiController::login()', $container);
    }
}
