<?php

namespace ContainerFTAD4Pv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEtudiantApiControllersendStudentsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TYOTLPM.App\Controller\API\EtudiantApiController::sendStudents()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TYOTLPM.App\\Controller\\API\\EtudiantApiController::sendStudents()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'student' => ['privates', 'App\\Repository\\StudentsRepository', 'getStudentsRepositoryService', true],
        ], [
            'student' => 'App\\Repository\\StudentsRepository',
        ]))->withContext('App\\Controller\\API\\EtudiantApiController::sendStudents()', $container);
    }
}
