<?php

namespace ContainerFTAD4Pv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oUPLUKJ.App\Controller\TaskController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oUPLUKJ.App\\Controller\\TaskController::index()'] = ($container->privates['.service_locator.oUPLUKJ'] ?? $container->load('get_ServiceLocator_OUPLUKJService'))->withContext('App\\Controller\\TaskController::index()', $container);
    }
}
