<?php

namespace Container0F6Jo2C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddRoleCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\AddRoleCommand' shared autowired service.
     *
     * @return \App\Command\AddRoleCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\AddRoleCommand'] = $instance = new \App\Command\AddRoleCommand(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:add-role');

        return $instance;
    }
}
