<?php

namespace Container0F6Jo2C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBanWordValidatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Validator\BanWordValidator' shared autowired service.
     *
     * @return \App\Validator\BanWordValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Validator\\BanWordValidator'] = new \App\Validator\BanWordValidator();
    }
}
