<?php

namespace Container0F6Jo2C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\DeleteService' shared autowired service.
     *
     * @return \App\Service\DeleteService
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\DeleteService'])) {
            return $container->privates['App\\Service\\DeleteService'];
        }

        return $container->privates['App\\Service\\DeleteService'] = new \App\Service\DeleteService($a);
    }
}
