<?php

namespace Container0F6Jo2C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectApiControllerupdateService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.8i9eKYQ.App\Controller\API\ProjectApiController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8i9eKYQ.App\\Controller\\API\\ProjectApiController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\ProjectRepository', 'getProjectRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'repository' => 'App\\Repository\\ProjectRepository',
            'em' => '?',
            'serializer' => '?',
        ]))->withContext('App\\Controller\\API\\ProjectApiController::update()', $container);
    }
}
