<?php

namespace Container0F6Jo2C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSemestreRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\SemestreRepository' shared autowired service.
     *
     * @return \App\Repository\SemestreRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SemestreRepository'] = new \App\Repository\SemestreRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
