<?php

namespace Container0F6Jo2C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskControllerpaginateService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.oUPLUKJ.App\Controller\TaskController::paginate()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oUPLUKJ.App\\Controller\\TaskController::paginate()'] = ($container->privates['.service_locator.oUPLUKJ'] ?? $container->load('get_ServiceLocator_OUPLUKJService'))->withContext('App\\Controller\\TaskController::paginate()', $container);
    }
}
