<?php

namespace Container0F6Jo2C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskControllereditService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.kt6nDhg.App\Controller\TaskController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kt6nDhg.App\\Controller\\TaskController::edit()'] = ($container->privates['.service_locator.kt6nDhg'] ?? $container->load('get_ServiceLocator_Kt6nDhgService'))->withContext('App\\Controller\\TaskController::edit()', $container);
    }
}
