<?php

namespace Container0F6Jo2C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserApiControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\API\UserApiController' shared autowired service.
     *
     * @return \App\Controller\API\UserApiController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\API\\UserApiController'] = $instance = new \App\Controller\API\UserApiController(($container->privates['App\\Service\\JwtTokenManager'] ??= new \App\Service\JwtTokenManager($container->getEnv('JWT_SECRET'))));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\API\\UserApiController', $container));

        return $instance;
    }
}
