<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAP0vP6P\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAP0vP6P/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAP0vP6P.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAP0vP6P\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAP0vP6P\App_KernelDevDebugContainer([
    'container.build_hash' => 'AP0vP6P',
    'container.build_id' => '6551f90b',
    'container.build_time' => 1733390646,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAP0vP6P');
